[build]
  base = "dynamic-book-frontend"
  command = "npm install && npm run build -- --configuration production"
  publish = "dist/dynamic-book-frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"